name:                api
version:             0.0.0
author:              "Anderson"
license:             MIT
extra-source-files:  []
build-type:          Simple
resolver:            lts-22.27

executables:
  api-exe:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - servant
      - servant-server
      - aeson
      - warp
      - wai
